### PR TITLE
Fix up bindings after update to 2.18.1

### PR DESCRIPTION
**Pull request by ArchangelWTF**
### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines 
- [ ] Relevant documentation was updated
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by ArchangelWTF** [comment]
@martijn00 Here you go, all projects seem to build successfully :)

**Review by martijn00 — APPROVED** [review]

**Comment by martijn00** [comment]
Nice work! Do you have any Github actions experience? I would love to get this running on Actions so releases are easier to create.

**Comment by ArchangelWTF** [comment]
I've not used anything related to Github Actions before so I'm afraid I cannot help there.

**Comment by martijn00** [comment]
No problem, I'll try and set it up. If you want to help a bit more, I think some of the bindings could be cleaned because there is quite some outdated metadata.

**Pull request merged**
