### PR TITLE
Add MonoAndroid support along with MAUI

### PR DESCRIPTION
**Pull request by ArchangelWTF**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Allows ExoPlayerXamarin to support both MonoAndroid and MAUI at the same time

### :arrow_heading_down: What is the current behavior?
ExoPlayerXamarin only supports MAUI

### :boom: Does this PR introduce a breaking change?
Not that I know of.

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines 
- [x] Relevant documentation was updated
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by martijn00** [comment]
Hmmm, I love the effort you put in but I find it hard to pull this into the code base and a release because long term this is more difficult to support. People should move to .net6 or 7 anyways. Why would this be a good idea?

**Comment by ArchangelWTF** [comment]
Considering that MonoAndroid wont be End of Life until 2024 (Which means load od people will be still stuck in the migration of XF to MAUI) I'd say this is a perfect compromise where we can build for both somewhat painlessly.

I propose just supporting it for as long as ExoPlayerXamarin compiles with it (Meaning that the bindings dont get too complex for mono) I'll happily even maintain it since it wasn't too big of an issue to get it working in the way i've made it work above.

**Comment by ArchangelWTF** [comment]
Woops wasn't meant to press that, damn mobile phone.

**Comment by sschaub** [comment]
@martijn00 I hope you'll consider accepting this PR. While it's true that MAUI is the future, there are good reasons for projects not to move to it just yet. Articles such as [this one](https://visualstudiomagazine.com/articles/2022/09/29/net-maui-complaints.aspx) indicate that MAUI is still not quite ready for prime time. In the meantime, Xamarin users who aren't ready to make the switch would benefit from having the latest ExoPlayer releases available to them.

**Comment by martijn00** [comment]
I've been thinking about this. What about creating a new xamarin branch and releasing seperate nugets from there with a suffix -xamarin in the release title? Long term I wouldn't want to maintain the old stuff as it begins to break more and more.

**Comment by martijn00** [comment]
Yes, but the update process will be done by Github Actions, so not a problem there. Also you can see in the bindings now that there need to be separate fixes for both. I rather have 1 point of truth and backport that to the Xamarin version.

**Comment by janwiebe-jump** [comment]
Hi everyone. Best wishes for 2023 🎉 
Is having a separate branch for the Xamarin version of ExoPlayerXamarin the way to go now?

**Comment by martijn00** [comment]
@ArchangelWTF @janwiebe-jump  i've done some changes to support both from 1 codebase (hopefully), i'm not sure if all the metadata changes are now correct in the xamarin branch? Could you check and if possible make a PR?

When it works like i hope it would, i will enable: https://github.com/Baseflow/ExoPlayerXamarin/blob/develop/.github/workflows/dotnet.yml#L45

**Comment by janwiebe-jump** [comment]
LGTM! Thanks so much!

**Comment by martijn00** [comment]
For some reason dotnet pack doesn't work: MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

**Comment by janwiebe-jump** [comment]
@martijn00 I ran into this earlier. Looks like the Xamarin projects cant be built with dotnet build / pack.
building with MSBuild should generate the packages, which can then be pushed with a dotnet nuget push

https://github.com/Baseflow/ExoPlayerXamarin/pull/147/files#diff-19a29f4e3c34d5224ac8726575c7750eb84080a5b97cd58439fdac6c13dda7c6

**Comment by martijn00** [comment]
But i do build with msbuild. I want to use dotnet pack to re pack the already build nupkg

**Pull request closed without merging**
